# Получение токена по username & password.
# "token": "4898f1fdee7db9a38376ad717bcefb3914070949". 
# Логин и пороль можно получить: python manage.py createsuperuser
POST http://62.84.117.214:9001/api-token-auth/
Content-Type: application/json

{
    "username": "zomin",
    "password": "Vitaliya"
}

###
POST http://62.84.117.214:9001/api/v1/category/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{
    "title": "HDD",
    "description": "Жесткие диски"
}
###
POST http://62.84.117.214:9001/api/v1/category/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{
    "title": "Videocard",
    "description": "Видеокарты"
}
###
GET  http://62.84.117.214:9001/api/v1/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949
###
GET  http://62.84.117.214:9001/api/v1/category/2/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949
###
PATCH http://62.84.117.214:9001/api/v1/category/1/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{
    "id": 1,
    "title": "HDD_2",
    "description": "Жесткие диски"
}

###  -------------------name---------------------
POST http://62.84.117.214:9001/api/v1/name/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{
    "category": 2,
    "mod_name": "Gforce 3080ti ASUS Tuf 12gb",
    "price": "175000",
    "mod_detail": "5555555"
}
###
POST http://62.84.117.214:9001/api/v1/name/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{
    "category": 1,
    "mod_name": "HDD 1Tb WD",
    "price": "3500",
    "mod_detail": "666666"
}
###
GET  http://62.84.117.214:9001/api/v1/name/1/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949
###
GET  http://62.84.117.214:9001/api/v1/name/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949
###
PATCH  http://62.84.117.214:9001/api/v1/name/1/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{
    "category": 2,
    "mod_name": "Gforce 3080ti Palit Gamerock 12gb",
    "price": "180000",
    "mod_detail": "111111"
}

###  ---------------Item----------------------
POST  http://62.84.117.214:9001/api/v1/post_items_serial/1/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{  
    "model_items": [
    {
      "serial_num": 666666666667
    },
    {
      "serial_num": 666666666666
    }
  ]
}
### 
GET  http://62.84.117.214:9001/api/v1/item/9/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949
###
GET  http://62.84.117.214:9001/api/v1/item/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949
### 
DELETE  http://62.84.117.214:9001/api/v1/item/8/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949
###
DELETE   http://62.84.117.214:9001/api/v1/delete_items_serial/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{  
    "model_items": [
    {
      "serial_num": 666666666667
    },
    {
      "serial_num": 666666666666
    }
  ]
}
###
DELETE   http://62.84.117.214:9001/api/v1/alt_delete_items_serial/
Content-Type: application/json
Authorization: Token 4898f1fdee7db9a38376ad717bcefb3914070949

{  
    "model_items": [
    {
      "serial_num": 666666666667
    },
    {
      "serial_num": 666666666666
    }
  ]
}