# Generated by Django 2.2.19 on 2022-04-26 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Категория')),
                ('description', models.TextField(max_length=256, verbose_name='Описание Категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'default_related_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(max_length=64, verbose_name='Модель товара')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Цена товара', null=True, verbose_name='Цена')),
                ('mod_detail', models.TextField(max_length=256, verbose_name='Описание Товара')),
                ('mod_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, upload_to='magazine/', verbose_name='Картинка')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_name', to='store.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Молель товара',
                'verbose_name_plural': 'Модели товаров',
                'default_related_name': 'item_model',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('Magaz', 'Magazine'), ('Store', 'Store'), ('In_magaz', 'From store in magazine'), ('Order', 'Order and wait purchase'), ('Sold', 'Sold in magazine')], default='Store', max_length=32, verbose_name='Место нахожднения/Статус')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер телефона и имя')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('name', models.ForeignKey(blank=True, help_text='Модель товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_items', to='store.Name', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-pub_date',),
            },
        ),
    ]
