# Generated by Django 2.2.19 on 2022-04-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Magaz', 'Magazine'), ('Store', 'Store'), ('in_magaz', 'From store in magazine'), ('wait', 'Purchased and wait in magazine'), ('order', 'Order and wait purchase'), ('sold', 'Sold in magazine')], default='Store', max_length=32, verbose_name='Место нахожднения/Статус'),
        ),
        migrations.AlterField(
            model_name='name',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_name', to='magazine.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='name',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='name',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Цена товара', null=True, verbose_name='Цена'),
        ),
    ]
