name: Computer_store workflow

on: [push]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          source: "infra_store/docker-compose.yaml, infra_store/default.conf"
          target: "/home/zomini/"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          rm: true
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
              cd infra_store/
              sudo infra_store/docker-compose stop
              sudo infra_store/docker-compose rm -f web
              sudo infra_store/docker-compose up -d --build
              sudo infra_store/docker-compose exec -T web python manage.py collectstatic --noinput
