name: Computer_store workflow

on: [push]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          source: "docker-compose.yaml, default.conf, .env"
          target: "/home/zomini/"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
              sudo docker-compose stop
              sudo docker-compose rm -f web
              sudo docker-compose up -d --build
              sudo docker-compose exec web python manage.py migrate --noinput
              sudo docker-compose exec web python manage.py collectstatic --noinput

